name: llm-sql
channels:
  - defaults
  - conda-forge

dependencies:
  - annotated-types=0.7.0
  - anyio=4.9.0
  - bcrypt=4.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - click=8.1.8
  - cryptography=44.0.2
  - diskcache=5.6.3
  - dnspython=2.7.0
  - email-validator=2.2.0
  - exceptiongroup=1.2.2
  - fastapi=0.115.12
  - fastapi-cli=0.0.7
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.6
  - libblas
  - libcblas
  - libffi=3.4.4

  - liblapack 
  - libopenblas
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libuv=1.50.0
  - libzlib

  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.4 
  - numpy=2.2.5
  - openssl=3.5.0
  - pandas=2.2.3
  - paramiko=3.5.1
  - pip=25.0
  - pycparser=2.22
  - pydantic=2.11.3
  - pydantic-core=2.33.1
  - pydantic-settings=2.9.1
  - pygments=2.19.1
  - pynacl=1.5.0
  - python=3.10 
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-multipart=0.0.20
  - python-tzdata=2025.2

  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - rich=14.0.0
  - rich-toolkit=0.11.3
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.45.2
  - sse-starlette=2.3.3
  - starlette=0.46.2
  - starlette-context=0.3.6
  - tk=8.6.13
  - typer=0.15.2
  - typing-extensions=4.13.2
  - typing-inspection=0.4.0
  - tzdata=2025a
  - uvicorn=0.34.2
  - uvloop=0.21.0
  - watchfiles=1.0.5
  - websockets=15.0.1
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - llama-cpp-python==0.3.8